In [5]:
#here we will start with loops
#while loop

n=0
while n<10
    n+=1
    print(n," ")
end
println("")
fibo = [0,1,1,2,3,5,8,13]
i=1
while i<=length(fibo)
    new = fibo[i]
    print("$new ")
    i+=1
end
#In julia indexing starts with 1


1 2 3 4 5 6 7 8 9 10 


0 1 1 2 3 5 8 13 

In [7]:
#for loop
for parth in 1:10
    print(parth," ")
end

1 2 3 4 5 6 7 8 9 10 

In [14]:
#addition tables
m,n = 5,5
A = zeros(m,n)
for i in 1:m
    for j in 1:n
        A[i,j]=i+j
    end
end
A
#creating the exact same addition table above effectively
B=zeros(3,3)
for i in 1:3,j in 1:3
    B[i,j] = i+j
end
B

#here we will do by array comprehension
C = [i+j for i in 1:m,j in 1:n]
C




5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [16]:
#here we will implements array comprehension in a for loop
for n in 1:5
    A=[i+j for i in 1:n,j in 1:n]
    display(A)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [4]:
##here we will be using conditional statements
x = 40
y = 54
if x>y
    println("$x is greater than $y")
else
    println("$y is greater than $x")
end

#we can also use ternanry operatorss for this

54 is greater than 40


ErrorException: syntax: space required before colon in "?" expression